language: crystal
dist: xenial
sudo: true
addons:
  apt:
    packages:
      - openjdk-8-jdk
      - openjdk-8-jre
before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb
  - sudo service elasticsearch start
  - sleep 10
  - crystal ./script/runner.cr -- es:index:create_all

notifications:
  on_failure: never
  on_success: never
